name: helloworld

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.10'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Display Hello World!
        run: python3 helloworld.py
     # - name: build docker
     #  run: docker build -t helloworld-app -f ./Dockerfile .
      - name: Login to the Container Registry  
        uses: azure/docker-login@v1
        with:
          login-server: ${{ AZURE_CREDENTIALS.ACR_LOGIN_SERVER }}
          username: ${{ AZURE_CREDENTIALS.REGISTRY_USERNAME }}
          password: ${{ AZURE_CREDENTIALS.REGISTRY_PASSWORD }}
      - name: Build and Tag image
        run: |
          docker build -f ./Dockerfile -t ${{ secrets.ACR_LOGIN_SERVER }}/helloworld:${{ github.run_number }} .
      - name: Scan image
        uses: Azure/container-scan@v0
        with:
          image-name: ${{ AZURE_CREDENTIALS.ACR_LOGIN_SERVER }}/helloworld:${{ github.run_number }}
          severity-threshold: CRITICAL
          run-quality-checks: true  
      - name: Push image
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/helloworld:${{ github.run_number }}
